---
# tasks file for mapr-resourcemanager

- name: install mapr-resourcemanager
  yum: name={{item}} state=present
  with_items:
    - mapr-resourcemanager
  environment: proxy_env

- name: check whether warden is running
  command: service mapr-warden status
  register: warden_status
  failed_when: warden_status.rc not in (0,1)
  changed_when: false

- name: install a correct yarn-site.xml from template
  template: src=yarn-site.xml.j2 dest=/opt/mapr/hadoop/hadoop-2.4.1/etc/hadoop/yarn-site.xml backup=yes
  register: install_yarn_site_xml
  when: mapr_version in ('v4.0.1')

- name: find hadoop version
  shell: rpm -qa --queryformat '%{VERSION} %{RELEASE}' mapr-hadoop-core | awk '{ print substr($0,0,5) }'
  register: hadoop_version
  changed_when: false

- name: configure proxyuser groups
  hadoop_properties: file=/opt/mapr/hadoop/hadoop-{{hadoop_version.stdout}}/etc/hadoop/core-site.xml name=hadoop.proxyuser.mapr.groups value=*
  when: secure_cluster is defined and secure_cluster == "True"

- name: configure proxyuser hosts
  hadoop_properties: file=/opt/mapr/hadoop/hadoop-{{hadoop_version.stdout}}/etc/hadoop/core-site.xml name=hadoop.proxyuser.mapr.hosts value=*
  when: secure_cluster is defined and secure_cluster == "True"
